"""
AI Market Analyst & Comparative Evaluator:
Evaluates competing candidate setups from the Trade Opportunity Engine.
Explicitly answers the 6 mandatory institutional questions:
1. WHY THIS TRADE
2. WHY NOW
3. WHERE THE LIQUIDITY IS
4. WHERE THE INVALIDATION IS
5. WHERE THE TARGET LIQUIDITY IS
6. WHAT WOULD MAKE THIS TRADE WRONG

Operates strictly in an ADVISORY comparative role.
CANNOT alter Stop Loss, Take Profit, Lot Size, Risk limits, or open orders directly.
Returns structured JSON only with calibrated confidence and reason codes.
"""

import json
import httpx
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from app.config import settings
from app.services.setup_families import CandidateSetup
from app.services.confidence_calibration import confidence_calibrator
from app.services.empirical_expectancy import EmpiricalExpectancyEngine, SampleEvidenceTier


class InstitutionalTradeAudit(BaseModel):
    why_this_trade: str
    why_now: str
    where_the_liquidity_is: str
    where_the_invalidation_is: str
    where_the_target_liquidity_is: str
    what_would_make_this_trade_wrong: str


class ComparativeCandidateEval(BaseModel):
    candidate_id: str
    symbol: str
    setup_family: str
    verdict: str  # "CHOSEN", "REJECTED_LOWER_EV", "DEFERRED", "INSUFFICIENT_EVIDENCE", "NO_EDGE"
    empirical_expectancy_r: float = 0.0
    evaluation_notes: str


class StructuredRankingItem(BaseModel):
    rank: int
    candidate_id: str
    symbol: str
    setup_family: str
    score: float
    reason: str


class ComparativeAnalysisResult(BaseModel):
    selected_candidate: Optional[str] = None
    selected_winner_id: Optional[str] = None  # Backward compatibility
    action: str = "WAIT"  # "TRADE", "WAIT", "NO_TRADE"
    confidence: float = 0.0
    calibrated_confidence: float = 0.0
    reason_codes: List[str] = Field(default_factory=list)
    risk_flags: List[str] = Field(default_factory=list)
    ranking: List[StructuredRankingItem] = Field(default_factory=list)
    comparative_justification: str = ""
    institutional_audit: Optional[InstitutionalTradeAudit] = None
    competing_candidates_eval: List[ComparativeCandidateEval] = Field(default_factory=list)
    reviewer_name: str = "ComparativeEvaluator"


class AIComparativeEvaluator:
    """
    Decoupled AI Analyst for multi-candidate trade comparison with strict execution guardrails.
    """

    def __init__(self, api_key: Optional[str] = None, model: Optional[str] = None):
        self.api_key = api_key or getattr(settings, "llm_api_key", None)
        self.model = model or getattr(settings, "llm_model", "anthropic/claude-3.5-sonnet")

    async def evaluate_candidates(
        self,
        candidates: List[CandidateSetup],
        account_summary: Optional[Dict[str, Any]] = None,
        context_features: Optional[Dict[str, Any]] = None
    ) -> ComparativeAnalysisResult:
        """
        Conducts comparative evaluation of candidate setups.
        Guarantees that the LLM only advises on selection, never modifies execution rules.
        """
        if not candidates:
            return self._empty_result("No candidate setups presented for evaluation.")

        top_candidates = candidates[:5]

        # If OpenRouter key is not available or placeholder, use algorithmic statistical comparative evaluation
        if not self.api_key or self.api_key in ["", "placeholder", "your_openrouter_api_key", "your_api_key"]:
            return self._deterministic_comparative_eval(top_candidates, account_summary)

        prompt = f"""
You are the Chief Investment Officer and Quantitative Analyst at an institutional SMC hedge fund.
Compare the following competing trade candidates generated by our deterministic opportunity engine.
Select the single best trade or recommend WAIT / NO_TRADE if edge is insufficient or risk flags exist.

CANDIDATES:
"""
        for idx, c in enumerate(top_candidates, 1):
            prompt += f"""
Candidate {chr(64 + idx)} (ID: {c.id}):
- Symbol: {c.symbol} ({c.timeframe}) | Setup Family: {c.setup_family}
- Direction: {c.direction} ({c.order_type}) | Entry: {c.entry_price} | SL: {c.stop_loss} | TP: {c.take_profit}
- Risk/Reward: 1:{c.risk_reward:.1f} | Expected Value: +{c.expected_value:.2f}R | Quality Score: {c.setup_quality_score}/100
- Invalidation: {c.invalidation_level} | Target Liquidity: {c.target_liquidity_level}
- Confluences: {', '.join(c.confluence_factors)}
"""

        prompt += """
MANDATORY RULES:
1. You may NOT alter Entry, Stop Loss, Take Profit, or Lot Size.
2. If all candidates have low quality, excessive spread, or high risk, return action="WAIT" or "NO_TRADE".
3. Provide confidence between 30 and 95%.

Return ONLY valid JSON matching this schema:
{
  "selected_candidate": "CANDIDATE_ID_OR_NULL",
  "action": "TRADE" | "WAIT" | "NO_TRADE",
  "confidence": 75.0,
  "reason_codes": ["STRONG_HTF_ALIGNMENT", "LIQUIDITY_CLEARED"],
  "risk_flags": [],
  "ranking": [
    {"rank": 1, "candidate_id": "...", "symbol": "...", "setup_family": "...", "score": 85.0, "reason": "..."}
  ],
  "comparative_justification": "Clear explanation",
  "institutional_audit": {
    "why_this_trade": "...",
    "why_now": "...",
    "where_the_liquidity_is": "...",
    "where_the_invalidation_is": "...",
    "where_the_target_liquidity_is": "...",
    "what_would_make_this_trade_wrong": "..."
  }
}
"""

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
            "HTTP-Referer": "https://trade-z.com",
            "X-Title": "Trade-Z Comparative Analyst",
        }

        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": "You are a quantitative trading evaluator. Output strictly valid JSON."
                },
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.15,
            "max_tokens": 900,
        }

        try:
            async with httpx.AsyncClient(timeout=8.0) as client:
                resp = await client.post("https://openrouter.ai/api/v1/chat/completions", headers=headers, json=payload)
                if resp.status_code == 200:
                    raw_text = resp.json()["choices"][0]["message"]["content"].strip()
                    if "```json" in raw_text:
                        raw_text = raw_text.split("```json")[1].split("```")[0].strip()
                    elif "```" in raw_text:
                        raw_text = raw_text.split("```")[1].split("```")[0].strip()

                    parsed = json.loads(raw_text)
                    sel_id = parsed.get("selected_candidate")
                    raw_conf = float(parsed.get("confidence", 70.0))
                    cal_conf = confidence_calibrator.calibrate_confidence(raw_conf)
                    act = parsed.get("action", "TRADE").upper()

                    # Audit: If calibrated confidence drops below 60%, convert TRADE to WAIT
                    if act == "TRADE" and cal_conf < 60.0:
                        act = "WAIT"
                        parsed.setdefault("risk_flags", []).append("CALIBRATED_CONFIDENCE_BELOW_THRESHOLD")

                    ranking_items = [
                        StructuredRankingItem(
                            rank=r.get("rank", idx + 1),
                            candidate_id=r.get("candidate_id", ""),
                            symbol=r.get("symbol", ""),
                            setup_family=r.get("setup_family", ""),
                            score=float(r.get("score", 70.0)),
                            reason=r.get("reason", "")
                        )
                        for idx, r in enumerate(parsed.get("ranking", []))
                    ]

                    audit_data = parsed.get("institutional_audit", {})
                    audit_obj = InstitutionalTradeAudit(
                        why_this_trade=audit_data.get("why_this_trade", "SMC structural alignment"),
                        why_now=audit_data.get("why_now", "Prerequisites completed at bar close"),
                        where_the_liquidity_is=audit_data.get("where_the_liquidity_is", "Mapped structural extremes"),
                        where_the_invalidation_is=audit_data.get("where_the_invalidation_is", "Structural swing high/low"),
                        where_the_target_liquidity_is=audit_data.get("where_the_target_liquidity_is", "Opposing imbalance/pool"),
                        what_would_make_this_trade_wrong=audit_data.get("what_would_make_this_trade_wrong", "Displacement crossing invalidation")
                    )

                    return ComparativeAnalysisResult(
                        selected_candidate=sel_id,
                        selected_winner_id=sel_id,
                        action=act,
                        confidence=raw_conf,
                        calibrated_confidence=cal_conf,
                        reason_codes=parsed.get("reason_codes", ["AI_ADVISORY_COMPARATIVE_APPROVAL"]),
                        risk_flags=parsed.get("risk_flags", []),
                        ranking=ranking_items,
                        comparative_justification=parsed.get("comparative_justification", ""),
                        institutional_audit=audit_obj,
                        competing_candidates_eval=[],
                        reviewer_name=f"OpenRouter ({self.model})"
                    )
        except Exception as e:
            print(f"[AIComparativeEvaluator] AI call failed ({e}), using deterministic statistical evaluation.")

        return self._deterministic_comparative_eval(top_candidates, account_summary)

    def _deterministic_comparative_eval(
        self,
        top_candidates: List[CandidateSetup],
        account_summary: Optional[Dict[str, Any]] = None
    ) -> ComparativeAnalysisResult:
        """
        Algorithmic comparative evaluation based purely on quantitative metrics and empirical edge.
        Does NOT hallucinate win probability.
        """
        # Sort candidates primarily by empirical expected value, then setup quality score
        sorted_cands = sorted(
            top_candidates,
            key=lambda c: (getattr(c, "expected_value", 0.0), c.setup_quality_score),
            reverse=True
        )
        winner = sorted_cands[0]

        # Check whether the top candidate has sufficient statistical edge
        ev = getattr(winner, "expected_value", 0.0)
        action = "TRADE"
        reason_codes = ["STATISTICAL_EDGE_CONFIRMED", f"EV_+{ev:.2f}R"]
        risk_flags = []

        if winner.setup_quality_score < 70:
            action = "WAIT"
            reason_codes = ["QUALITY_SCORE_BELOW_70"]
            risk_flags.append("SUB_OPTIMAL_QUALITY")
        elif ev < 0.20 and getattr(winner, "sample_size", 0) >= 50:
            action = "NO_TRADE"
            reason_codes = ["NEGATIVE_OR_MARGINAL_EXPECTANCY"]
            risk_flags.append("NO_EMPIRICAL_EDGE")

        raw_conf = float(winner.setup_quality_score)
        cal_conf = confidence_calibrator.calibrate_confidence(raw_conf)

        ranking: List[StructuredRankingItem] = []
        competing: List[ComparativeCandidateEval] = []

        for idx, c in enumerate(sorted_cands, 1):
            c_ev = getattr(c, "expected_value", 0.0)
            if c.id == winner.id and action == "TRADE":
                verdict = "CHOSEN"
                notes = f"Selected: Superior EV (+{c_ev:.2f}R) and Quality Score ({c.setup_quality_score}/100)."
            else:
                verdict = "REJECTED_LOWER_EV" if action == "TRADE" else "DEFERRED"
                notes = f"Lower ranking vs {winner.symbol} (+{c_ev:.2f}R vs +{ev:.2f}R)."

            competing.append(ComparativeCandidateEval(
                candidate_id=c.id,
                symbol=c.symbol,
                setup_family=c.setup_family,
                verdict=verdict,
                empirical_expectancy_r=c_ev,
                evaluation_notes=notes
            ))

            ranking.append(StructuredRankingItem(
                rank=idx,
                candidate_id=c.id,
                symbol=c.symbol,
                setup_family=c.setup_family,
                score=float(c.setup_quality_score),
                reason=notes
            ))

        justification = (
            f"Candidate on {winner.symbol} ({winner.setup_family}) evaluated against {len(sorted_cands)} competing setups. "
            f"Action: {action}. Expectancy: +{ev:.2f}R, 1:{winner.risk_reward:.1f} R:R, Calibrated Confidence: {cal_conf:.1f}%."
        )

        audit = InstitutionalTradeAudit(
            why_this_trade=f"{winner.setup_family} on {winner.symbol} with {', '.join(winner.confluence_factors[:2])}.",
            why_now=f"Price completed structural setup prerequisites at {winner.entry_price:.5f}.",
            where_the_liquidity_is=f"Resting liquidity mapped between {winner.invalidation_level:.5f} and {winner.target_liquidity_level:.5f}.",
            where_the_invalidation_is=f"Defined at {winner.invalidation_level:.5f}.",
            where_the_target_liquidity_is=f"Targeted at {winner.target_liquidity_level:.5f} providing 1:{winner.risk_reward:.1f} R:R.",
            what_would_make_this_trade_wrong=f"Closing beyond {winner.invalidation_level:.5f} or sudden macroeconomic shock."
        )

        return ComparativeAnalysisResult(
            selected_candidate=winner.id if action == "TRADE" else None,
            selected_winner_id=winner.id if action == "TRADE" else None,
            action=action,
            confidence=raw_conf,
            calibrated_confidence=cal_conf,
            reason_codes=reason_codes,
            risk_flags=risk_flags,
            ranking=ranking,
            comparative_justification=justification,
            institutional_audit=audit,
            competing_candidates_eval=competing,
            reviewer_name="DeterministicComparativeEngine"
        )

    def evaluate_candidates_sync(
        self,
        candidates: List[CandidateSetup],
        account_summary: Optional[Dict[str, Any]] = None
    ) -> ComparativeAnalysisResult:
        """
        Synchronous deterministic evaluation of candidate setups using quantitative metrics and empirical edge.
        """
        if not candidates:
            return self._empty_result("No candidate setups presented for evaluation.")
        return self._deterministic_comparative_eval(candidates[:5], account_summary)

    def _empty_result(self, msg: str = "No candidates found.") -> ComparativeAnalysisResult:
        return ComparativeAnalysisResult(
            selected_candidate=None,
            selected_winner_id=None,
            action="NO_TRADE",
            confidence=0.0,
            calibrated_confidence=0.0,
            reason_codes=["NO_CANDIDATES_AVAILABLE"],
            risk_flags=[],
            ranking=[],
            comparative_justification=msg,
            institutional_audit=None,
            competing_candidates_eval=[],
            reviewer_name="None"
        )


# Global evaluator instance
comparative_evaluator = AIComparativeEvaluator()
