import type { Plan } from '@trade-z/types';

// ============================================================================
// Subscription Plan Definitions
// ============================================================================

export const PLANS: Plan[] = [
  {
    id: 'free',
    name: 'Free',
    description: 'Get started with basic AI trading signals',
    price: 0,
    currency: 'USD',
    interval: 'month',
    isPopular: false,
    features: [
      { name: 'AI Market Analysis', included: true },
      { name: 'Up to 5 signals/day', included: true },
      { name: 'Basic confidence scoring', included: true },
      { name: 'Manual trading mode', included: true },
      { name: '1 paper trading account', included: true },
      { name: 'Trade journal', included: true },
      { name: 'Semi-automatic mode', included: false },
      { name: 'Fully automatic mode', included: false },
      { name: 'Live broker connections', included: false },
      { name: 'AI Chat assistant', included: false },
      { name: 'Priority support', included: false },
    ],
    limits: {
      maxSignalsPerDay: 5,
      maxOpenTrades: 3,
      maxBrokerConnections: 1,
      aiChatMessages: 0,
      historicalDataDays: 30,
      customAlerts: 3,
      advancedAnalytics: false,
      prioritySupport: false,
      apiAccess: false,
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    description: 'Full AI trading power for serious traders',
    price: 49,
    currency: 'USD',
    interval: 'month',
    isPopular: true,
    features: [
      { name: 'AI Market Analysis', included: true },
      { name: 'Unlimited signals', included: true },
      { name: 'Advanced confidence scoring', included: true },
      { name: 'All trading modes', included: true },
      { name: 'Up to 5 broker connections', included: true },
      { name: 'Trade journal with AI insights', included: true },
      { name: 'Semi-automatic mode', included: true },
      { name: 'Fully automatic mode', included: true },
      { name: 'Live broker connections', included: true },
      { name: 'AI Chat assistant (500 msgs/mo)', included: true },
      { name: 'Priority support', included: false },
    ],
    limits: {
      maxSignalsPerDay: -1, // unlimited
      maxOpenTrades: 20,
      maxBrokerConnections: 5,
      aiChatMessages: 500,
      historicalDataDays: 365,
      customAlerts: 50,
      advancedAnalytics: true,
      prioritySupport: false,
      apiAccess: false,
    },
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    description: 'Maximum power for professional traders',
    price: 199,
    currency: 'USD',
    interval: 'month',
    isPopular: false,
    features: [
      { name: 'Everything in Pro', included: true },
      { name: 'Unlimited AI Chat', included: true },
      { name: 'Unlimited broker connections', included: true },
      { name: 'API access', included: true },
      { name: 'Custom AI strategies', included: true },
      { name: 'Advanced analytics', included: true },
      { name: 'White-label options', included: true },
      { name: 'Dedicated account manager', included: true },
      { name: 'Priority support', included: true },
      { name: 'Custom integrations', included: true },
      { name: 'SLA guarantee', included: true },
    ],
    limits: {
      maxSignalsPerDay: -1,
      maxOpenTrades: -1,
      maxBrokerConnections: -1,
      aiChatMessages: -1,
      historicalDataDays: -1,
      customAlerts: -1,
      advancedAnalytics: true,
      prioritySupport: true,
      apiAccess: true,
    },
  },
];
